name: com.minecarts.worldoverseer.WorldOverseer
main: com.minecarts.worldoverseer.com.minecarts.worldoverseer.WorldOverseer
version: ${pom.version}
website: http://minecarts.com
author: Verrier
depend: [DBQuery]
description: A plugin to manage certain world attributes
commands:
    overseer:
        description: Access to the bouncer functions
        usage: /<command>
permissions:
    worldoverseer.admin:
        description: "Administrative command access to com.minecarts.worldoverseer.WorldOverseer"
        default: op